### ISSUE TITLE
missing SoftReset.h?

### ISSUE THREAD

**Issue by zeukterialpneumaion** [eclab/gizmo#1]
the All.h specifies a SoftReset.h which isn't in your repo...causing the .ino to fail ...
- fantastic work though! thankyou! working on storage with sdcard..j

**Comment by eclab** [comment]
Softreset.h is in the SoftReset library which Gizmo's got packed in libraries/SoftReset.zip.  Unzip that library and stick it in your Arduino directory, just like the Midi library.

Let me know how the sdcard bit goes!  You may have to tweak how we specify a file index since the sdcard can hold so much more.  We'd have to think about how to do that right GUI-wise.

Sean

**Comment by fraser1950** [comment]
Trying to build for a Mega, found that the Synth.h & .cpp files are missing.  I was able to get around it by commenting out synth.h the INCLUDE_SYNTH and INCLUDED SYNTHS.  Didn't know if the omission was on purpose or just an oversight.

Thank-you for creating this.  It appears to be an amazing amount of work.  I look forward to getting this built and running.

**Comment by eclab** [comment]
Sorry, try now.

**Comment by eclab** [comment]
Any further results with the sd card?

Sean

**Comment by zeukterialpneumaion** [comment]
Hi Sean! Great... haven't had a chance to look at sd yet....life
intervened! On the mission though.. also thinking of using fram...

**Comment by fraser1950** [comment]
Builds without problem now, thank-you
