### ISSUE TITLE
De-mirror display

### ISSUE THREAD

**Issue by danielblues** [eclab/gizmo#7]
Hi,
I've bought this display https://www.aliexpress.com/item/4000369735317.html
It works "ok" but has an inverted display.
Not in a simple way, fixable with ROTATE_WHOLE_SCREEN, but it scrolls from left to right and the letters are mirrored like this:

```
***** ***** ***** *****
    * *   * *   * *   *
***** ***** ***** *****
    *     *   * * *   *
*****     * *   * *   *
```

Any way to fix this? (without using a mirror ;)
Thank you
Daniel

**Comment by SeanLuke** [comment]
So here's what I'd do.  In LEDDisplay.cpp there is a function called 

    void sendMatrix(unsigned char* matrix, unsigned char* matrix2, uint8_t i2cAddress = I2C_ADDRESS_1, uint8_t i2cAddress2 = I2C_ADDRESS_2)

There are different versions of this function depending on the kind of matrix being used.  I'd take the SCREEN_TYPE_ADAFRUIT_16x8_BACKPACK version and modify that.

This function does some optional rotation and then sends both 8x8 LED matrix arrays using Wire.write.  The arrays are called matrix and matrix2 respectively.  What you need to do is (1) reverse each matrix, then (2) swap the matrices with one another before writing them, that is, set matrix2 to matrix and matrix to matrix2.

To reverse the matrix, I think all you have to do is swap the bytes, along these lines:

    for(uint8_t i = 0; i < 4; i++)
        { uint_t temp = matrix[i]; matrix[i] = matrix[7-i]; matrix[7-i] = temp; }

If this is swapping in the wrong direction (by Y rather than X), you will instead need to reverse each byte instead.  I don't think this is the case?  But who knows.  See [this stack overflow entry](https://stackoverflow.com/questions/2602823/in-c-c-whats-the-simplest-way-to-reverse-the-order-of-bits-in-a-byte/2602871) for a fun way to do that.

**Comment by danielblues** [comment]
That worked! 

```
    // De-mirror the display
    for(uint8_t i = 0; i < 4; i++)
        { 
        uint8_t temp = matrix[i]; 
        uint8_t temp2 = matrix2[i]; 
        
        matrix[i] = matrix2[7-i];
        matrix2[i] = matrix[7-i];
         
        matrix[7-i] = temp2;
        matrix2[7-i] = temp; 
        }
```

Made a "SCREEN_TYPE_MJKDZ_16x8_BACKPACK" based on on the SCREEN_TYPE_ADAFRUIT_16x8_FEATHERWING_BACKPACK because the display looked near the expected result.
Is a pull for this useful?
Thank you.
Best,

**Comment by eclab** [comment]
So... I just committed a flip function you could use.  Lemme know if it works.

Instead of a pull request, just send me the version of sendMatrix you wrote here as a posting, ideally using the new flip function, and lemme think about how or whether to integrate it.

Sean

**Comment by danielblues** [comment]
It worked fine,

```
    flipMatrix(matrix, FLIP_X);
    flipMatrix(matrix2, FLIP_X);
    unsigned char* temp = matrix;
    matrix = matrix2;
    matrix2 = temp;
```

Placed here:

```
#ifdef SCREEN_TYPE_MJKDZ_16x8_BACKPACK
// i2cAddress2 is ignored
void sendMatrix(unsigned char* matrix, unsigned char* matrix2, uint8_t i2cAddress = I2C_ADDRESS_1, uint8_t i2cAddress2 = I2C_ADDRESS_2)
    {
    // rotate as necessary
    uint8_t mat[8];
    uint8_t mat2[8];

#ifdef ROTATE_WHOLE_SCREEN
    // swap the two matrices. We'll rotate each one 180 later. This results in a full rotation of the combined screen
    unsigned char* temp = matrix;
    matrix = matrix2;
    matrix2 = temp;
#endif ROTATE_WHOLE_SCREEN

    // the display of the matrices is rotated 90 degrees, so we need to tweak here
    if (rotation >= DIR_180)  // rotate to 180 if we're DIR_180 or DIR_COUNTERCLOCKWISE_90, nothing else
        {
        memcpy(mat, matrix, 8);
        memcpy(mat2, matrix2, 8);
        rotateMatrix(mat, DIR_NONE);
        rotateMatrix(mat2, DIR_NONE);
        matrix2 = mat;  // note we're flipping them
        matrix = mat2;
        }
    else    // other rotations are considered DIR_NONE
        {
        memcpy(mat, matrix, 8);
        memcpy(mat2, matrix2, 8);
        rotateMatrix(mat, DIR_180);
        rotateMatrix(mat2, DIR_180);
        matrix2 = mat;  
        matrix = mat2;
        }

#ifdef ROTATE_WHOLE_SCREEN
    // rotate the two matrices. We swapped them earlier. This results in a full rotation of the combined screen
    rotateMatrix(matrix, DIR_180);
    rotateMatrix(matrix2, DIR_180);
#endif ROTATE_WHOLE_SCREEN

    flipMatrix(matrix, FLIP_X);
    flipMatrix(matrix2, FLIP_X);
    unsigned char* temp = matrix;
    matrix = matrix2;
    matrix2 = temp;

    Wire.beginTransmission(i2cAddress);
    Wire.write(0);

    for (uint8_t i=0; i<8; i++) 
        {
        Wire.write(matrix2[i]);    
        Wire.write(matrix[i]);    
        }
    Wire.endTransmissionNonblocking();  
    blinkToggle++;
    if (blinkToggle > blinkOff)
        blinkToggle = 0;
    }
#endif SCREEN_TYPE_MJKDZ_16x8_BACKPACK
```

**Comment by SeanLuke** [comment]
I've committed your code, now in LEDDisplay.cpp.
